name: Python build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  create:
    branches: [main]
    tags: ['**']

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7, 3.8, 3.9]
    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Update pip and wheel
      run: python -m pip install --upgrade pip wheel

    - uses: actions/checkout@v2
    - name: Build sdist
      run: python setup.py sdist
    - name: Install sdist
      run: pip install ./dist/pybv-*
    - name: Clean up working directory
      run: rm -rf ./*
    - name: Try importing pybv
      run: python -c 'import pybv; print(pybv.__version__)'
    - name: Remove sdist install
      run: pip uninstall -y pybv

    - uses: actions/checkout@v2
    - name: Build wheel
      run: python setup.py bdist_wheel
    - name: Install wheel
      run: pip install ./dist/pybv-*.whl
    - name: Clean up working directory
      run: rm -rf ./*
    - name: Try importing pybv
      run: python -c 'import pybv; print(pybv.__version__)'
    - name: Remove wheel install
      run: pip uninstall -y pybv
